apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
  annotations:
    seccomp.security.alpha.kubernetes.io/pods: "runtime/default" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      # automountServiceAccountToken: false
      serviceAccountName: dso-demo
      containers:
      - image: sabre1409/dsodemo
        name: dsodemo
        ports:
        - containerPort: 8080
        securityContext:
          # seccompProfile:
          #   type: RuntimeDefault
          capabilities:
            drop: 
              - ALL
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          # Should be set very high to make sure id is not the same as process on host
          runAsUser: 11000
        resources:
         requests:
          cpu: "50m"
          memory: "128Mi"
         limits:
          cpu: "250m"
          memory: "256Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
status: {}